### ISSUE TITLE
bug: CORS err

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/keats-frontend#7]
![image](https://user-images.githubusercontent.com/52108077/127447293-af2c5782-162c-42b3-a847-e9848b8e7ca8.png)
@KrishChatterjie I got a random CORS error specifically for this book.

**Comment by KrishChatterjie** [comment]
Yess that's meant to happen, must blame @mdhishaamakhtar for adding random stuff to database without using the website :/ Won't be repeated when tables are reset and people actually follow the steps 🙄

**Comment by mdhishaamakhtar** [comment]
Yes this is not an issue. The data is bs and was inserted even before website **designs** were made. So yeah. This will not happen.

**Comment by mdhishaamakhtar** [comment]
@Nirmitjatana I would request you to close this issue
